### PR TITLE
Display the country dial code next to the selected flag

### PR DESCRIPTION
**Pull request by zaizac**
Added separateDialCode (#170) input field to allow user to choose to display the dial code next to the selected flag. Parse phoneNumber value and remove the dial code in input text

### CODE REVIEW

**Comment by pasevin** [comment]
Hey thanks for this, can you check the last update and if it solves your issue. If no can you address the conflicts?

**Comment by zaizac** [comment]
Conflicts resolved. I have added as well **searchCountryPlaceholder** input field for user to add placeholder on the search country field.

**Comment by zaizac** [comment]
> Hey thanks for this, can you check the last update and if it solves your issue. If no can you address the conflicts?

Conflicts resolved. I have added as well searchCountryPlaceholder input field for user to add placeholder on the search country field.

**Comment by zaizac** [comment]
Conflicts resolved and Included some changes:

- Added as well **searchCountryPlaceholder** input field for the placeholder on search country field.
- Fixed for Issue #195

**Comment by pasevin** [comment]
Thanks @zaizac, i'm trying to understand what this pull request is actually doing, but can't understand :]]] Can you quickly show me with a few sentences or a screenshot? Sorry, to bother :)

**Comment by zaizac** [comment]
image

This is my result.

**Comment by zaizac** [comment]
Hi, I have fixed the design and update the demo app

image

**Comment by pasevin** [comment]
Thanks, I still see layout issues with longer dial codes:
image

The best approach would be to make those elements relative to each other instead of absolute. Not sure if it's possible.

**Comment by zaizac** [comment]
I am using the existing css styling from intl-tel-input.css. But I have adjusted the arrow position on separate dial code.

image

Also, I update demo app and added reset button to reset the input from it's initial state.

**Comment by zaizac** [comment]
Please check issue #176, I think it is fixed as well related to my changes at country-code.ts

**Comment by pasevin** [comment]
Hey, check my PR with proposed different approach to styling of separate dial code and input. It's not ideal, but I think it's better to have consistent widths and paddings regardless of font or dial code length.

**Comment by pasevin** [comment]
And regarding issue #176 i'm not sure, we should ask people from that issue to test and ask if that fixed their problem.

**Pull request merged**
