### PR TITLE
Fix peer dep warning for Angular 11

### LINKED ISSUE #354: Angular 11 support
Hi guys!
We want to use your library in our project but unfortunately, we are on Angular 11. Are you guys working on releasing support for Angular 11?

### PR DESCRIPTION
**Pull request by crutchcorn**
Fixes #354 

We're currently using this dependency with our Angular 11 app without any issues. This PR updates the peer dep semver range and dev tools deps.

### CODE REVIEW

**Comment by crutchcorn** [comment]
@pasevin are we able to get this merged in sometime this week?

I'm actually leaving the role that's using this in their app and it's the only peerDep left in the dep tree. I'd love to leave instructions for how to migrate to npm 7, which requires this PR to be merged first due to npm 7's shifted behavior in peer deps

**Comment by pasevin** [comment]
Hey @crutchcorn thanks for this. Have you checked if this doesn't break previous versions of Angular? Or does this need to be set as a separate branch ```angular-11```?

**Comment by pasevin** [comment]
Thanks again @crutchcorn, will publish this on npm asap.

**Comment by crutchcorn** [comment]
Apologies for not responding sooner about Angular <10 compat - I'm admittedly not sure 😅 

Thanks for publishing so quickly! I appreciate it :)

**Pull request merged**
