### PR TITLE
Move to angular 14

### PR DESCRIPTION
**Pull request by nicolasleb**
Hello,

It is a migration of the library to accept Angular 14.

Regards

### CODE REVIEW

**Comment by itseramin** [comment]
Please merge.

**Comment by 64623203** [comment]
@webcat12345 Is there anything in the way of releasing this? I need to move to Angular 14, and this package is unfortunately a blocker.

**Comment by dnapp** [comment]
@webcat12345 Could you please merge? Angular 15 was just released so it would be great if we could continue moving forward.

**Comment by lea-elhage** [comment]
Would it be possible to merge as I would love to use this package with angular 14

**Comment by webcat12345** [comment]
Busy days for some business. @nicolasleb I added you as a collaborator. You can handle this PR. Also let me know your NPM account so you can publish as well.

**Comment by TofanIulian** [comment]
@nicolasleb, @webcat12345,
The peerDependencies were overlooked leading to incompatibility with angular 14 projects. Please review [481](https://github.com/webcat12345/ngx-intl-tel-input/pull/481)

**Comment by kevynsax** [comment]
Any News when this will be published as a NPM package?

**Pull request merged**
