### PR TITLE
Angular 13 update

### PR DESCRIPTION
**Pull request by NayeBeckham**
Solves [#410](https://github.com/webcat12345/ngx-intl-tel-input/issues/410)

**What's the problem**
The application wasn't up-to-date and it could make problems.

**Why we should fix it**
It should be fixed because we can have new features, optimizations and the bugs there are in old versions can be fixed.

**How I fixed it**
I ran the command `npx @angular/cli@13 update @angular/core@13 @angular/cli@13` in the terminal.
Then, I ran the command `npm install --force` to set all the final changes.
Ran the command `ng serve` to see if everything was working as normal.

How package.json should see now:

Screen Shot 2021-12-17 at 8 38 44
Screen Shot 2021-12-17 at 8 38 56

Everyone with angular 13 should be able to use this library.

Thank you, feel free to tell me anything.

### CODE REVIEW

**Comment by phyr0s** [comment]
@NayeBeckham  hello, you need to change peerDependencies to 

`. "@angular/common": "8.x - 13.x",
		"@angular/core": "8.x - 13.x",
		"@angular/forms": "8.x - 13.x",
		"google-libphonenumber": "^3.2.3",
`

**Comment by phyr0s** [comment]
@NayeBeckham  also you can not generate the library only changing ng-packagr version. There is breaking changes --> umdModuleIds is not longer available

https://github.com/ng-packagr/ng-packagr/blob/master/CHANGELOG.md#200-2018-02-05

**Comment by diiogocosta** [comment]
I think it can be merged right?

**Comment by phyr0s** [comment]
@diiogocosta  no, can't be merged until fixed the peerDependencies and removing umdModuleIds.

**Comment by NayeBeckham** [comment]
@phyr0s hello, I made some changes and I think it is working now!

I added the peerDependencies as you suggested
Screen Shot 2022-01-12 at 12 11 06

And I created two angular projects from scratch to see if everything is working correctly.
At the angular 13 project I followed all the installation steps and everything was working fine, I changed the library peerDependencies and I added the necessary imports at the `app.module.ts` and everything was working.
Screen Shot 2022-01-12 at 12 12 31
There wasn't any console error.
Screen Shot 2022-01-12 at 12 16 33

At the angular 8 project I also followed all the installation steps, changed the library peerDependencies, and added the necessary imports.
Screen Shot 2022-01-12 at 12 18 14

But here I was having trouble importing `ChangeData` and `Country`. And what I did was remove the `type` at `import`.
Like this:
Screen Shot 2022-01-12 at 12 18 02

There wasn't any console error.
Screen Shot 2022-01-12 at 12 20 55

Hope it helps, thank you for the feedback!

**Comment by phyr0s** [comment]
Looks better @NayeBeckham

@webcat12345 can you check it?

**Comment by james-bampoe** [comment]
Is there anything missing for the pull request to be merged? Would be great to have support for Angular 13 soon :)

**Comment by hugopicq** [comment]
When can we hope to see this lib in Angular 13 ?

**Comment by Aionx** [comment]
Hello @webcat12345, can we hope for this request to be merged anytime soon ? We need this to work on Angular 13 so bad ! Thanks by advance !

**Comment by pelkamarcin** [comment]
Hey, @phyr0s can you recheck this one?

**Comment by paulagrisolia-tc** [comment]
Is there a way to merge this soon?

**Comment by samwilcock** [comment]
Can this be merged please, would be great to have it in v13.

**Comment by phyr0s** [comment]
@webcat12345 people are waiting

**Comment by vbxhunn** [comment]
Hi, any update regarding this?

**Comment by Tharunvarshanth** [comment]
@webcat12345  @phyr0s we are also waiting for this merge to work on  angular-13 please merge as soon as possible

**Comment by sreeragspillai** [comment]
Any update on this?

**Comment by Gubancs** [comment]
I'm also waiting for this update, i appreciate your help.

**Comment by webcat12345** [comment]
Sorry here!!! Just came back to this PR and reviewing it now, seems like there are bunch of webpack pack files, not sure what are those. Any comment on it?

**Comment by webcat12345** [comment]
Thank you all for contributing our library, I am ready to publish this to new version, but before it want to clarify about those pack files.

**Comment by webcat12345** [comment]
And for the consistency, I would insist to use single quote mark, rather than double quote mark. Could you please fix them?

**Comment by NayeBeckham** [comment]
@webcat12345 I think the changes as you requested are ready, I deleted all the webpacks and there wasn't problem :)

**Review by webcat12345 — APPROVED** [review]

**Comment by webcat12345** [comment]
Hi webcat!

A new version of the package ngx-intl-tel-input (3.2.0) was published at 2022-04-06T14:51:15.547Z from
188.43.136.42. The shasum of this package was c2d8dc683408b550d5ba571df633890294ee33c8.

If you have questions or security concerns, you can contact us at https://www.npmjs.com/support.

Thanks,

The npm team.

**Pull request merged**
