### PR TITLE
Add option for providing unique input ID

### PR DESCRIPTION
**Pull request by bdwellons**
Add option for providing unique input ID.

### CODE REVIEW

**Comment by kristofferabell** [comment]
+1

**Comment by pasevin** [comment]
Thanks!

**Comment by bdwellons** [comment]
@pasevin Thanks for merging! When will you be pushing a new release version to NPM registry?

**Comment by pasevin** [comment]
I need to find time to package and publish npm. I was tight on time for the past few months...
Maybe this weekend :)

**Comment by pasevin** [comment]
I had to make some additional fixes, but now new version is published on npm as v2.3.3

**Pull request merged**
